### ISSUE TITLE
issues with snapshots

### ISSUE THREAD

**Issue by georgemoralis** [stephanrauh/BootsFaces-Examples#1]
I am trying to run your latest samples using 0.8.0 snapshot
I have added the following to my pom.xml

```
    <repository>
        <id>bootfaces-repo</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>

    <dependency>
        <groupId>net.bootsfaces</groupId>
        <artifactId>bootsfaces</artifactId>
        <version>0.8.0-SNAPSHOT</version>
    </dependency>
```

However i am getting a lot of error of missing attributes . I have cleared netbeans cache my local maven repo but i can't find solution ;/

For example in ajax sample 

carousel.xhtml

The attribute update is not defined in the component carousel
The attribute onmousover is not defined in the component carouselItem

checkbox.xhtml

The attribute update is not defined in the component selectBooleanCheckbox
The attribute onvaluechange is not defined in the component selectBooleanCheckbox
The attribute onmouseselect is not defined in the component selectBooleanCheckbox

i am using netbeans 8.1 btw

**Comment by stephanrauh** [comment]
What does "is not defined" mean? Is it missing in the autocomplete list of NetBeans, or doesn't it work if you use the attribute?

At the moment I'm a bit in a hurry, so maybe you can help me. Please have a look at the taglib file (https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/meta/META-INF/bootsfaces-b.taglib.xml) and check if the attributes are there or not. NetBeans read this file to compose its autocompletion list. (BTW, you're right, Carousel.update is missing in the taglib). Next you can check the https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/xtext/BootsFaces.jsfdsl file. That's the list of attributes I wanted to implement. If the attribute is in the *.jsfdsl file, it's almost certain that you can use it, even if NetBeans tells you something different. 

If you want to be sure, check the component class (in this case https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/component/carousel/Carousel.java). If there's a getter/setter pair, you can use the attributes. Sometimes we forget to evaluate it in the renderer, but that's another story. In this case, getUpdate() and setUpdate() are there.

It's always a bit tedious and error-prone to copy the attribute list into the taglib file, so errors happen every once in a while. For some reason, autocompletion doesn't work at all on my PC, so I don't even notice the missing attributes :(.

**Comment by georgemoralis** [comment]
it is not only the autocomplete but it doesn't work either...

For example the latest addition i asked for iconAwesome in dropmenu is not working with latest snapshot

I can see it exists in BootsFaces.jsfdsl  but not in bootsfaces-b.taglib.xml

process in commandbutton also exists in jsfdl but not in taglib.xml

**Comment by stephanrauh** [comment]
Thanks for your help! I still suspect that NetBeans is the problem. Some time ago someone told me that the attributes don't work in NetBeans if they are missing in the taglib. Eclipse doesn't mind. I suggest you grab the showcase application (https://github.com/TheCoder4eu/BootsFacesWeb) and try to get it work. That should be easy, it's a simple Maven application running in a Tomcat. The showcase doesn't cover every attribute, but as far as I remember the iconAwesome attribute in dropMenu is demonstrated. Obviously, the showcase runs (http://www.bootsfaces.net/Staging/). If you run into trouble nonetheless, it's a NetBeans problem, and I have to rebuild the taglib file quickly.

**Comment by georgemoralis** [comment]
hmm now i am puzzled .  i ran the showcase application , and seems that attributes is reading correctly here... (i can see the icon in dropmenu , ajax in commandbutton sample appears to work ok).

Maybe it's some setting in pom.xml ? :/

**Comment by nahummor** [comment]
Hi, I encountered a similar problem,i'm using Netbeans 8.1 jsf 2.2 bootsfaces 0.8.0 maven.
when i use  b:commandButten the attribute <b>process</b> does not appear in the attribute list.
in the b:column the attribute <b>colLg</b> , <b>colMd</b>  , <b>colSm</b>  and<b> colXs</b>  don't work'
instead, I use <b>class="col-lg-2"</b>.

**Comment by stephanrauh** [comment]
After more than half a year and several versions of BootsFaces, I suppose this issue has been solved in the meantime, so I'll close it.
